# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.3'

gem 'acts_as_votable'
gem 'administrate', '>= 0.14', '< 1.0'
gem 'administrate-field-active_storage'
gem 'bcrypt'
gem 'blueprinter'
gem 'bootsnap', '>= 1.4.4', require: false
gem 'ckeditor'
gem 'data_migrate'
gem 'dotenv-rails'
gem 'faker'
gem 'faraday'
gem 'image_processing'
gem 'interactor-rails'
gem 'jwt_sessions'
gem 'kaminari'
gem 'mini_magick'
gem 'paranoia'
gem 'pg', '~> 1.1'
gem 'pg_search'
gem 'puma', '~> 5.0'
gem 'rack-cors'
gem 'rails', '~> 6.1'
gem 'redis', '~> 4'
gem 'rswag-api'
gem 'rswag-ui'
gem 'sidekiq', '>= 6.0'
gem 'whenever', require: false

# --- Ништяки, чтобы в любой среде не сломать глаза при попытке посмотреть содержимое моделей
gem 'hirb'
gem 'pry-rails'
# ---

group :development, :test do
  gem 'awesome_print'
  gem 'factory_bot_rails'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'rswag-specs'
end

group :development do
  gem 'capistrano', '~> 3.15.0', require: false
  gem 'capistrano-bundler'
  gem 'capistrano-passenger'
  gem 'capistrano-rails', require: false
  gem 'capistrano-rails-console', require: false
  gem 'capistrano-rvm'
  gem 'capistrano-sidekiq'
  gem 'letter_opener'
  gem 'listen', '~> 3.3'
  gem 'rubocop-performance'
  gem 'rubocop-rails'
  gem 'rubocop-rspec'
  gem 'spring'
end

group :test do
  gem 'simplecov', require: false
end

gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
