# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 7
  timeout: 10000

development:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_DEV_NAME'] %>
  host:     <%= ENV['DB_DEV_HOST'] %>
  port:     <%= ENV['DB_DEV_PORT'] %>

test:
  <<: *default
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_TEST_NAME'] %>
  host:     <%= ENV['DB_TEST_HOST'] %>
  port:     <%= ENV['DB_TEST_PORT'] %>

production:
  <<: *default
  database: <%= ENV['DB_PROD_NAME'] %>
  username: <%= ENV['DB_PROD_USERNAME'] %>
  password: <%= ENV['DB_PROD_PASSWORD'] %>
